import Head from "next/head";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Services from "@/components/Services";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className="px-8 pb-8 lg:px-16 lg:pb-16">
        {/* About */}
        <About />
        {/* Services */}
        <Services />
        {/* Footer */}
      </div>
      <Footer />
    </>
  );
}
